import resolve from 'rollup-plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import babel from '@rollup/plugin-babel'
import {terser} from 'rollup-plugin-terser'
import license from 'rollup-plugin-license'

import pkg from './package.json'

const banner = `
<%= pkg.name %> <%= pkg.version %>
MIT Licensed 
Generated by <%= pkg.authors[0] %>
Generated at <%= moment().format('YYYY-MM-DD') %>
`

export default [
  {
    input: 'src/index.js',
    external: ['lodash'],
    output: [
      {
        name: 'whyDidYouRender',
        file: pkg.main,
        format: 'umd',
        sourcemap: true,
        exports: 'default',
        globals: {
          lodash: 'lodash'
        }
      }
    ],
    plugins: [
      babel({
        exclude: 'node_modules/**',
        babelHelpers: 'bundled'
      }),
      resolve(),
      commonjs(),
      terser(),
      license({
        sourcemap: true,
        banner
      })
    ]
  }
]
